apiVersion: v1
kind: ServiceAccount
metadata:
  name: koder
  namespace: koder
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: koder
  namespace: koder
rules:
  - apiGroups: ["", "apps"]
    resources: ["deployments", "namespaces"]
    verbs:
      - list
      - get
      - patch
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: koder
  namespace: koder
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: koder
subjects:
  - kind: ServiceAccount
    name: koder
    namespace: koder
